using SudokuSolver.Library;

namespace SudokuSolver.Tests;

public class PuzzleParserTests
{
    // Known test puzzle from the problem statement
    private const string SamplePuzzleString = "400050000105076009060400050900000510500090006027000008050004020200360104000010005";
    private const string SampleSolution     = "479158362135276489862439751984623517513897246627541938751984623298365174346712895";

    [Fact]
    public void Parse_SimpleString_WithZeros()
    {
        var grid = PuzzleParser.Parse(SamplePuzzleString);
        Assert.Equal(Grid.TotalCells, CountNonZero(grid) + CountZero(grid));
        Assert.Equal(4, grid[0, 0]);
        Assert.Equal(0, grid[0, 1]);
    }

    [Fact]
    public void Parse_SimpleString_WithDots()
    {
        var dots = SamplePuzzleString.Replace('0', '.');
        var grid = PuzzleParser.Parse(dots);
        Assert.Equal(4, grid[0, 0]);
        Assert.Equal(0, grid[0, 1]);
    }

    [Fact]
    public void Parse_SimpleString_RoundTrip()
    {
        var grid = PuzzleParser.Parse(SamplePuzzleString);
        Assert.Equal(SamplePuzzleString, grid.ToPuzzleString());
    }

    [Fact]
    public void Parse_GridFormat_NineLines()
    {
        // 9 lines of 9 characters
        var gridStr = string.Join("\n", Enumerable.Range(0, Grid.Size).Select(r =>
            new string(Enumerable.Range(0, Grid.Size)
                .Select(c => SamplePuzzleString[r * Grid.Size + c])
                .ToArray())));

        var grid = PuzzleParser.Parse(gridStr);
        Assert.Equal(SamplePuzzleString, grid.ToPuzzleString());
    }

    [Fact]
    public void Parse_GridFormat_WithSeparatorLines()
    {
        // Formatted grid with separator lines every 3 rows
        var sb = new System.Text.StringBuilder();
        for (int r = 0; r < Grid.Size; r++)
        {
            if (r > 0 && r % 3 == 0)
                sb.AppendLine("---+---+---");
            for (int c = 0; c < Grid.Size; c++)
            {
                if (c > 0 && c % 3 == 0) sb.Append('+');
                sb.Append(SamplePuzzleString[r * Grid.Size + c]);
            }
            sb.AppendLine();
        }

        var grid = PuzzleParser.Parse(sb.ToString());
        Assert.Equal(SamplePuzzleString, grid.ToPuzzleString());
    }

    [Fact]
    public void Parse_SdkFormat_WithComments()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Generated by SudokuSolver");
        sb.AppendLine("# Title: Test Puzzle");
        for (int r = 0; r < Grid.Size; r++)
        {
            for (int c = 0; c < Grid.Size; c++)
            {
                char ch = SamplePuzzleString[r * Grid.Size + c];
                sb.Append(ch == '0' ? '.' : ch);
            }
            sb.AppendLine();
        }

        var grid = PuzzleParser.Parse(sb.ToString());
        Assert.Equal(SamplePuzzleString, grid.ToPuzzleString());
    }

    [Fact]
    public void Parse_EmptyInput_ThrowsFormatException()
    {
        Assert.Throws<FormatException>(() => PuzzleParser.Parse(""));
    }

    [Fact]
    public void Parse_TooFewCells_ThrowsFormatException()
    {
        Assert.Throws<FormatException>(() => PuzzleParser.Parse("123456789"));
    }

    [Fact]
    public void Parse_WellKnownPuzzle_ParsesCorrectly()
    {
        // Another well-known puzzle
        const string puzzle = "530070000600195000098000060800060003400803001700020006060000280000419005000080079";
        var grid = PuzzleParser.Parse(puzzle);
        Assert.Equal(5, grid[0, 0]);
        Assert.Equal(3, grid[0, 1]);
        Assert.Equal(0, grid[0, 2]);
        Assert.Equal(puzzle, grid.ToPuzzleString());
    }

    [Fact]
    public void Parse_StringWithPipes_Parses()
    {
        // Some apps export with pipe separators
        var withPipes = "4..|.5.|...\n1.5|.76|..9\n.6.|4..|.5.\n---+---+---\n9..|...|51.\n5..|.9.|..6\n.27|...|..8\n---+---+---\n.5.|..4|.2.\n2..|36.|1.4\n...|.1.|..5";
        var grid = PuzzleParser.Parse(withPipes);
        Assert.Equal(SamplePuzzleString, grid.ToPuzzleString());
    }

    private static int CountNonZero(Grid grid)
    {
        int count = 0;
        for (int i = 0; i < Grid.TotalCells; i++)
            if (grid[i] != 0) count++;
        return count;
    }

    private static int CountZero(Grid grid)
    {
        int count = 0;
        for (int i = 0; i < Grid.TotalCells; i++)
            if (grid[i] == 0) count++;
        return count;
    }
}
